language: go
sudo: false
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'CREATE EXTENSION IF NOT EXISTS postgis; CREATE EXTENSION IF NOT EXISTS "uuid-ossp";' -U postgres -d travis_ci_test
