package sol

// Tokens holds SQL tokens that are used for compilation / AST parsing
const (
	AVG            = "AVG"
	COUNT          = "COUNT"
	CROSSJOIN      = "CROSS JOIN"
	DATE           = "DATE"
	DATEPART       = "DATE_PART"
	DELETE         = "DELETE"
	DISTINCT       = "DISTINCT"
	FROM           = "FROM"
	FULLOUTERJOIN  = "FULL OUTER JOIN"
	GROUPBY        = "GROUP BY"
	HAVING         = "HAVING"
	INNERJOIN      = "INNER JOIN"
	INSERT         = "INSERT"
	INTO           = "INTO"
	LEFTOUTERJOIN  = "LEFT OUTER JOIN"
	LIMIT          = "LIMIT"
	MAX            = "MAX"
	MIN            = "MIN"
	OFFSET         = "OFFSET"
	ORDERBY        = "ORDER BY"
	RIGHTOUTERJOIN = "RIGHT OUTER JOIN"
	SELECT         = "SELECT"
	SET            = "SET"
	STDDEV         = "STDDEV"
	SUM            = "SUM"
	UPDATE         = "UPDATE"
	VALUES         = "VALUES"
	VARIANCE       = "VARIANCE"
	WHERE          = "WHERE"
	WHITESPACE     = " "
)
